### ISSUE TITLE
Floats in vcd not rounded.

### ISSUE THREAD

**Issue by kubsztal** [WojciechRynczuk/vcdMaker#1]
Log file:
#81765500 FRDM.Sensors.Accelerometer.AccY 0.0634766 f
#82125493 FRDM.Sensors.Accelerometer.AccY 0.0830078 f

VCD file:
#81765500

r0.06347659999999999 FRDM.Sensors.Accelerometer.AccY
#82125493

r0.08300780000000001 FRDM.Sensors.Accelerometer.AccY

**Comment by endrjux** [comment]
I think we should just store floating point signals as strings so that nothing is done to them. Now we have a conversion string -> double -> string, which is not very useful and introduces mentioned issue.
