### ISSUE TITLE
RHEL not-friendly

### ISSUE THREAD

**Issue by scaprile** [WojciechRynczuk/vcdMaker#61]
Hi, this looks nice.
I run CentOS 7 (RHEL) and the RPMs don't install, the binaries don't run (both require a newer libc++) and the sources don't compile (the scripts require cmake 3 and rhel7 comes with cmake2.8)

Could you try to do something RHEL-friendly ?
Regards

**Comment by scaprile** [comment]
Thanks!
vcdMaker works like a charm
vcdMerge seems to work OK. Checking the output file, I see a 64-bit bus is generated where the example has a 32-bit one, so a diff does not properly work here... anyway, as far as I can see the output seems to be the same

Since the manual has instructions to install via RPM, which is more than straightforward, perhaps you would want to add instructions to install via zip/tar ?
I can write them if you want me to.

Thanks a lot.
BTW, you are right, it is safer to include a statically linked binary on a zip/tar (size permitting). If in doubt, then have two zips/tars ;^) 
Best regards

**Comment by WojciechRynczuk** [comment]
Yes, the original example file has been created on a 32-bit machine. We will update it in the next release to 64-bit. I like the suggestion about instructions regarding zip/tar It will be included as well. I will swap the official release file and close the issue.

Enjoy the tool. Thank you for your ideas and comments If we could help you in any way just let us know :)

**Comment by WojciechRynczuk** [comment]
The statically linked application is available for download on the main page.
